framework:
    secret: '%env(APP_SECRET)%'
    default_locale: en
    csrf_protection: true
    http_method_override: true
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
    php_errors:
        log: true
    cache:
    templating:
        engines:
            - twig
jwt_auth:
    domain: '%env(AUTH_DOMAIN)%'
    authorized_issuer: '%env(AUTHORIZED_ISSUER)%'
    api_identifier: '%env(AUTH_API_IDENTIFIER)%'

